var express = require('express');
var router = express.Router();

const nameList = [
{ 'id': '1.', 'Term' : 'DevSecOps', 'Explanation' : 'Incorporating security testing at each level of the software development procedure is known as devsecops.', 'Acknowledgement': 'Amazon Web Services, Inc. (n.d.). What is DevSecOps? - Developer Security Operations - AWS. [online] Available at: https://aws.amazon.com/what-is/devsecops/.'},
{ 'id': '2.', 'Term' : 'DevOps', 'Explanation' : 'The phrases "Development" and "Operations" are combined to form the term "DevOps." Promoting the growth and operation process together is part of the culture. ', 'Acknowledgement': 'www.javatpoint.com. (n.d.). DevOps Tutorial - javatpoint. [online] Available at: https://www.javatpoint.com/devops.'},
{ 'id': '3.', 'Term' : 'Terraform', 'Explanation' : 'Terraform is an infrastructure as code solution that makes it safe and effective to create, modify, and version cloud and on-premise resources. ', 'Acknowledgement': ' Hashicorp (n.d.). What is Terraform | Terraform | HashiCorp Developer. [online] What is Terraform | Terraform | HashiCorp Developer. Available at: https://developer.hashicorp.com/terraform/intro.'},
{ 'id': '4.', 'Term' : 'AIops', 'Explanation' : 'Artificial intelligence for IT operations is referred to as AIOps it is used in the context to describe the use of AI and ML technologies to enhance and streamline various processes related to IT operations and the creation of software. ', 'Acknowledgement': ' Cisco. (n.d.). What Is AIOps? Artificial Intelligence for IT Operations. [online] Available at: https://www.cisco.com/c/en/us/solutions/artificial-intelligence/what-is-aiops.html.'},
{ 'id': '5.', 'Term' : 'Agile', 'Explanation' : 'Agile refers to software development methodologies that prioritize iterative delivery, teamwork, ongoing planning, and continuous learning.  ', 'Acknowledgement': 'mijacobs (n.d.). What is Agile? - Azure DevOps. [online] learn.microsoft.com. Available at: https://learn.microsoft.com/en-us/devops/plan/what-is-agile.'},
{ 'id': '6.', 'Term' : 'Kubernetes', 'Explanation' : 'For controlling containerized applications and services, Kubernetes is a portable, adaptable, open-source platform that supports expressive configuration and orchestration. ', 'Acknowledgement': 'Kubernetes. (n.d.). Overview. [online] Available at: https://kubernetes.io/docs/concepts/overview/.'},
{ 'id': '7.', 'Term' : 'Docker', 'Explanation' : 'A tool for executing apps within containers is called Docker. Containers combine all the code and dependencies required for your program to function into a single file that will function identically on any machine. ', 'Acknowledgement': 'Heddings, A. (n.d.). What Does Docker Do, and When Should You Use It? [online] How-To Geek. Available at: https://www.howtogeek.com/devops/what-does-docker-do-and-when-should-you-use-it/.'},
{ 'id': '8.', 'Term' : 'Silos', 'Explanation' : 'A silo is a discrete area within a system where data is kept apart from other components of an organizations information and communication technology architecture, either consciously or unconsciously. ', 'Acknowledgement': ' Techopedia.com. (2020). What is a Silo? - Definition from Techopedia. [online] Available at: https://www.techopedia.com/definition/25939/silo.'},
{ 'id': '9.', 'Term' : 'Cloud Storage', 'Explanation' : ' Digital data is saved on servers located off-site in a kind of computer data storage known as cloud storage.', 'Acknowledgement': ' Google (n.d.). What is Cloud Storage & How Does it Work? [online] Google Cloud. Available at: https://cloud.google.com/learn/what-is-cloud-storage.'},
{ 'id': '10.', 'Term' : 'Microservices ', 'Explanation' : ' One such service in charge of software development is the microservice. It enables you to check the architecture for service and performance and aids in the identification of potential debugging issues.', 'Acknowledgement': 'mijacobs (n.d.). What are Microservices? - Azure DevOps. [online] learn.microsoft.com. Available at: https://learn.microsoft.com/en-us/devops/deliver/what-are-microservices.'},
{ 'id': '11.', 'Term' : 'Continuous Integration (CI) ', 'Explanation' : 'Automating the build and testing processes and often merging code changes into a common repository to find and fix integration problems as soon as they arise.', 'Acknowledgement': 'Atlassian (2019). What is Continuous Integration | Atlassian. [online] Atlassian. Available at: https://www.atlassian.com/continuous-delivery/continuous-integration.'}, 
{ 'id': '12.', 'Term' : 'Continuous Deployment (CD) ', 'Explanation' : 'a development of continuous integration that makes that code updates are automatically sent to production settings after clearing several vetting and approval phases.', 'Acknowledgement': 'www.synopsys.com. (n.d.). What Is CI/CD and How Does It Work? | Synopsys. [online] Available at: https://www.synopsys.com/glossary/what-is-cicd.html#:~:text=Continuous%20delivery%20(CD)%20is%20the.'}, 
{ 'id': '13.', 'Term' : 'INFRASTRUCTURE AS CODE ', 'Explanation' : 'a technique for managing and provisioning infrastructure using machine-readable configuration files rather than human procedures, resulting in deployments that are more effective and reliable.', 'Acknowledgement': 'RedHat (2022). What is Infrastructure as Code (IaC)? [online] www.redhat.com. Available at: https://www.redhat.com/en/topics/automation/what-is-infrastructure-as-code-iac. '}, 
{ 'id': '14.', 'Term' : 'Version Control ', 'Explanation' : 'the act of utilising version control tools like Git to monitor and manage changes to file configurations or the source code.', 'Acknowledgement': 'Atlassian (2019b). What is version control. [online] Atlassian. Available at: https://www.atlassian.com/git/tutorials/what-is-version-control. '}, 
{ 'id': '15.', 'Term' : 'Incident Management ', 'Explanation' : 'the act of promptly and methodically reacting to issues and outages and resolving them.', 'Acknowledgement': 'SafetyCulture. (n.d.). What is Incident Management? [online] Available at: https://safetyculture.com/topics/incident-management/. '}, 
{ 'id': '16.', 'Term' : 'Metrics ', 'Explanation' : 'The industry standard for assessing the dependability and calibre of software delivery inside an organisation is considered to be DevOps metrics. We will be able to locate bottlenecks that are delaying delivery and resulting in deployed code problems by monitoring these data. ', 'Acknowledgement': 'www.pluralsight.com. (n.d.). 11 key DevOps metrics to measure team success. [online] Available at: https://www.pluralsight.com/blog/teams/devops-metrics#:~:text=DevOps%20metrics%20are%20regarded%20as [Accessed 4 Aug. 2023]. '}, 
{ 'id': '17.', 'Term' : 'Deployment Pipeline ', 'Explanation' : 'a set of automated processes that code changes go through from development to deployment in production.', 'Acknowledgement': 'PagerDuty. (n.d.). What is a Deployment Pipeline? [online] Available at: https://www.pagerduty.com/resources/learn/what-is-a-deployment-pipeline/#:~:text=In%20software%20development%2C%20a%20deployment. '}, 
{ 'id': '18.', 'Term' : 'Configuration Management ', 'Explanation' : 'the method of automating system configuration management and tracking in order to preserve consistency and stability.', 'Acknowledgement': 'RedHat (2019). What is configuration management. [online] www.redhat.com. Available at: https://www.redhat.com/en/topics/automation/what-is-configuration-management. '}, 
{ 'id': '19.', 'Term' : 'Application Performance Monitoring', 'Explanation' : 'Applications behaviour and performance are tracked and analysed to find problems and fix them. ', 'Acknowledgement': 'Anderson, D. (2021). What is APM? Application performance monitoring in a cloud-native world. [online] Dynatrace news. Available at: https://www.dynatrace.com/news/blog/what-is-apm-2/. '}, 
{ 'id': '20.', 'Term' : 'GitOps ', 'Explanation' : 'a method of developing software where all system modifications are controlled by Git repositories, offering a declarative method of managing infrastructure and applications.', 'Acknowledgement': ' about.gitlab.com. (n.d.). What is GitOps? | GitLab. [online] Available at: https://about.gitlab.com/topics/gitops/.'}, 







];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'DevOps Glossary', sub: ' Glossary Terms and their Description ', names: nameList });
});

module.exports = router;
